apiVersion: v1
kind: Secret
metadata:
  name: app-secret-auto
type: Opaque
stringData:
  DB_USERNAME: RohitBhatt   # Write plain text here; Kubernetes converts it automatically
  DB_PASSWORD: Test@12345      # Plain text
